# Copyright (C) 2020 The ocluso Authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

.PHONY: build backend frontend test

build: backend frontend

run: build
	cd build/output && ./ocluso


backend: build_dir
	cd build/generated && go build -o ../output/ocluso main.go

frontend:
	cd build/generated && npm run build


test:
	cd core/backend && go test ./...
	{{ range .Modules }}cd modules/{{.}}/backend && go test ./...
	{{ end }}
	cd core/frontend && npm test
	{{ range .Modules }}cd modules/{{.}}/frontend && npm test
	{{ end }}


build_dir:
	mkdir -p build/output/frontend

clean:
	rm -r build/output
